feat: Attach url to portfolio page
reservoirprotocol/marketplace-v2 pull request #389
Opened 2023-11-09 18:03 UTC by r3lays

2023-11-09 18:06 UTC, pedromcunha requested changes

2023-11-09 18:06 UTC, pedromcunha commented on pages/portfolio/[[...address]].tsx
> +  useEffect(() => {
Makes more sense to change wherever we direct the user to the portfolio to a portfolio which contains the address in the url of the connected wallet.

2023-11-13 16:23 UTC, r3lays reviewed
lgtm

2023-11-17 15:31 UTC, pedromcunha approved these changes

2023-11-17 15:32 UTC, pedromcunha commented
There are some conflicts, otherwise LGTM

2023-11-17 18:56 UTC, merged